export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_FULFILLED = 'REGISTER_FULFILLED';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';

export const GET_TASK_TYPES_PENDING = 'GET_TASK_TYPES_PENDING';
export const GET_TASK_TYPES_FULFILLED = 'GET_TASK_TYPES_FULFILLED';
export const GET_TASK_TYPES_REJECTED = 'GET_TASK_TYPES_REJECTED';
export const ADD_TASK_TYPE_PENDING = 'ADD_TASK_TYPE_PENDING';
export const ADD_TASK_TYPE_FULFILLED = 'ADD_TASK_TYPE_FULFILLED';
export const ADD_TASK_TYPE_REJECTED = 'ADD_TASK_TYPE_REJECTED';

export const GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING';
export const GET_PROJECTS_FULFILLED = 'GET_PROJECTS_FULFILLED';
export const GET_PROJECTS_REJECTED = 'GET_PROJECTS_REJECTED';
export const ADD_PROJECT_PENDING = 'ADD_PROJECT_PENDING';
export const ADD_PROJECT_FULFILLED = 'ADD_PROJECT_FULFILLED';
export const ADD_PROJECT_REJECTED = 'ADD_PROJECT_REJECTED';
export const ADD_PROJECT_MEMBER_PENDING = 'ADD_PROJECT_MEMBER_PENDING';
export const ADD_PROJECT_MEMBER_FULFILLED = 'ADD_PROJECT_MEMBER_FULFILLED';
export const ADD_PROJECT_MEMBER_REJECTED = 'ADD_PROJECT_MEMBER_REJECTED';

export const SELECT_PROJECT_FULFILLED = 'SELECT_PROJECT_FULFILLED';

export const GET_PROJECT_TASKS_PENDING = 'GET_PROJECT_TASKS_PENDING';
export const GET_PROJECT_TASKS_FULFILLED = 'GET_PROJECT_TASKS_FULFILLED';
export const GET_PROJECT_TASKS_REJECTED = 'GET_PROJECT_TASKS_REJECTED';

export const ADD_TASK_PENDING = 'ADD_TASK_PENDING';
export const ADD_TASK_FULFILLED = 'ADD_TASK_FULFILLED';
export const ADD_TASK_REJECTED = 'ADD_TASK_REJECTED';
export const COMPLETE_TASK_PENDING = 'COMPLETE_TASK_PENDING';
export const COMPLETE_TASK_FULFILLED = 'COMPLETE_TASK_FULFILLED';
export const COMPLETE_TASK_REJECTED = 'COMPLETE_TASK_REJECTED';