export const GET_OVERDUE_TASKS_PENDING = 'GET_OVERDUE_TASKS_PENDING';
export const GET_OVERDUE_TASKS_FULFILLED = 'GET_OVERDUE_TASKS_FULFILLED';
export const GET_OVERDUE_TASKS_REJECTED = 'GET_OVERDUE_TASKS_REJECTED';

export const GET_UPCOMING_TASKS_PENDING = 'GET_UPCOMING_TASKS_PENDING';
export const GET_UPCOMING_TASKS_FULFILLED = 'GET_UPCOMING_TASKS_FULFILLED';
export const GET_UPCOMING_TASKS_REJECTED = 'GET_UPCOMING_TASKS_REJECTED';
